#MODULE_XCC_XC_FLAGS = $(XCC_XC_FLAGS)
#DEPENDENT_MODULES = lib_dsp
#VERSION = 0.0.1

def use_module(bld):
    sources = bld.path.ant_glob(['src/**/*.xc', 'src/**/*.c', 'src/**/*.S'])
    bld.env.MODULE_XCC_XC_FLAGS = ['-O2', '-g']
    bld.module(
        source=sources,
        includes=['api'],
        depends_on=['lib_dsp', 'lib_voice_toolbox'],
        version='1.4.0',
        optional_headers=['process_wav_conf.h'])
