def options(ctx):
        ctx.add_option('--target', action='store', default='test_wav.xe')

def configure(conf):
	conf.load('xwaf.compiler_xcc')
	conf.env.PROJECT_ROOT = '../../..'

def build(bld):
        target_path = 'bin/' + bld.options.target
	bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
	bld.env.XSCOPE = bld.path.find_resource('config.xscope')

	depends_on = ['audio_test_tools']
	bld.env.XCC_FLAGS = ['-O2', '-g', '-Wall', '-fcmdline-buffer-bytes=512', '-report']
	source = bld.path.ant_glob('src/**/*.xc')
	bld.program(source=source, depends_on=depends_on,target=target_path)
